version: "3.8"

services:
  web:
    build: ./webcbt-frontend
    ports: 
      - 3000:3000
  api:
    build: ./WebCbt-Backend
    ports:
      - 7198:80
    environment:                             # environ variables
      DB_URL: mariadb://db/webcbt            # value should be database connection string
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=r00t_p@ssw0rd
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=admin_user
      - MYSQL_DATABASE=webcbt_db
    ports: 
      - 3306:3306                          # default port for mariadb
    volumes: 
      - ./data:/var/lib/mysql

volumes:
  webcbt: